[[main]]
  name = "Projects"
  url = "/projects/"
  weight = -109

[[main]]
  name = "From My Library"
  url = "/books/"
  weight = -108

# Submenus are done this way: parent -> identifier

[[main]]
  name = "About"
  url = "/about/"
  weight = -106

